#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

curl -OL https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb
dpkg -i mysql-apt-config*
apt-get update
apt-get --allow-unauthenticated -y install mysql-server mysql-client


PXB_VERSION_OVERRIDE=24
wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
apt-get update && apt-get install -y gnupg gnupg2
dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
apt-get update
apt-get --allow-unauthenticated -y install percona-xtrabackup-${PXB_VERSION_OVERRIDE}

cat >/etc/mysql/conf.d/no_perf_schema.cnf <<_EOF_
[mysqld]
performance_schema = off

_EOF_

mv /etc/mysql/my.cnf.fallback /etc/mysql/my.cnf
chown mysql:mysql /etc/mysql/my.cnf
cat >/etc/mysql/my.cnf <<_EOF_
[mysql]

!includedir /etc/mysql/conf.d/
_EOF_

if [ -e /etc/init/mysql.conf ]; then
    rm -f /etc/init/mysql.conf
fi

systemctl enable mysql
