#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

GUEST_VENV=/opt/guest-agent-venv

# Install Python driver for Elasticsearch.
${GUEST_VENV}/bin/pip install elasticsearch
