#!/bin/sh

# PURPOSE: Install redis required package in guest-agent-venv

set -ex

if [ $GUEST_VENV ]
then
  echo "TRUNGNV $GUEST_VENV."
  # Install Python driver for MongoDB.
  $GUEST_VENV/bin/pip3 install pymongo>=3.0.2,!=3.1
fi

