#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

mv /etc/mysql/my.cnf.fallback /etc/mysql/my.cnf
chown -R mysql:mysql /var/lib/mysql
chown mysql:mysql /etc/mysql/my.cnf
cat >/etc/mysql/my.cnf <<_EOF_
[mysql]
[client]
port = 3306
socket = /var/run/mysqld/mysqld.sock

[mysqld_safe]
pid-file = /var/run/mysqld/mysqld.pid
socket = /var/run/mysqld/mysqld.sock
nice = 0

[mysqld]
user = mysql
port = 3306
basedir = /usr
datadir = /var/lib/mysql
log-error=/var/log/mysqld.log
tmpdir = /var/tmp
pid-file = /var/run/mysqld/mysqld.pid
socket = /var/run/mysqld/mysqld.sock
skip-external-locking = 1
key_buffer_size = 100M
max_allowed_packet = 2048K
thread_stack = 192K
thread_cache_size = 8
myisam-recover-options = BACKUP,FORCE
query_cache_type = 1
query_cache_limit = 1M
query_cache_size = 16M
innodb_data_file_path = ibdata1:10M:autoextend
innodb_buffer_pool_size = 300M
innodb_file_per_table = 1
innodb_log_files_in_group = 2
innodb_log_file_size=50M
innodb_log_buffer_size=25M
connect_timeout = 15
innodb_data_home_dir = /var/lib/mysql
wait_timeout = 120
join_buffer_size = 1M
read_buffer_size = 512K
read_rnd_buffer_size = 512K
sort_buffer_size = 1M
tmp_table_size = 32M
max_heap_table_size = 32M
table_open_cache = 512
table_definition_cache = 512
open_files_limit = 1024
max_user_connections = 200
max_connections = 200
default_storage_engine = innodb
local-infile = 0
server_id = 1652887340

[mysqldump]
quick = 1
quote-names = 1
max_allowed_packet = 16M

[isamchk]
key_buffer = 16M

!includedir /etc/mysql/conf.d/
_EOF_
