#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)
# create random password
PASSWDDB="$(openssl rand -base64 12)"
GUEST_USERNAME=${GUEST_USERNAME:-"ubuntu"}
GUEST_PASSWORD=${PASSWDDB:-"pa55word"}
DIB_INIT_SYSTEM=${DIB_INIT_SYSTEM:-"systemd"}
FILE=/home/trove/.guestagent.prepare.end

cat <<EOF >> /etc/.exporter.cnf
[client]
user=${GUEST_USERNAME}
password=${GUEST_PASSWORD}
EOF

if [ ${GUEST_EXPORTER} == True ]; then
    cat <<EOF >> /etc/enable_exporter.sh
#!/bin/bash
while [ ! -f "/home/trove/.guestagent.prepare.start" ]; do
sleep 5
done

FILE=/home/trove/.guestagent.prepare.end
if [ -f "$FILE" ]; then
    echo "Ignore create user"
else
    sleep 5
    mysql -e "CREATE USER '${GUEST_USERNAME}'@'%' IDENTIFIED BY '${GUEST_PASSWORD}';"
    mysql -e "GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO '${GUEST_USERNAME}'@'%' WITH MAX_USER_CONNECTIONS 3;"
    mysql -e "FLUSH PRIVILEGES;"
fi
EOF
    
fi

chown -R root:root /etc/enable_exporter.sh
chmod 4755 /etc/enable_exporter.sh

#wget -P /etc/ https://github.com/viettelidc-oss/mysqld_exporter/raw/master/proxysql_modified.deb
wget -P /etc/ http://210.211.127.206:1999/proxysql_modified.deb
chmod 777 /etc/proxysql_modified.deb
wget -P /etc/ https://github.com/viettelidc-oss/mysqld_exporter/raw/master/proxysql_setup.sh
wget -P /etc/ https://github.com/viettelidc-oss/mysqld_exporter/raw/master/proxysql_modified.sh
chmod 777 /etc/proxysql_setup.sh
chmod 777 /etc/proxysql_modified.sh

wget https://github.com/prometheus/mysqld_exporter/releases/download/v0.11.0/mysqld_exporter-0.11.0.linux-amd64.tar.gz
tar xvzf mysqld_exporter-0.11.0.linux-amd64.tar.gz
# Rename mysqld_exporter to avoid conflict with trove check mysqld_safe status
cd mysqld_exporter-0.11.0.linux-amd64 && sudo mv mysqld_exporter /usr/local/bin/db_exporter

case "$DIB_INIT_SYSTEM" in
    systemd)
        mkdir -p /usr/lib/systemd/system
        touch /usr/lib/systemd/system/mysql-exporter.service
        sed "s/GUEST_USERNAME/${GUEST_USERNAME}/g" ${SCRIPTDIR}/mysql-exporter.service > /usr/lib/systemd/system/mysql-exporter.service
        ;;
    upstart)
        install -D -g root -o ${GUEST_USERNAME} -m 0644 ${SCRIPTDIR}/mysql-exporter.conf /etc/init/mysql-exporter.conf
        ;;
    sysv)
        install -D -g root -o ${GUEST_USERNAME} -m 0644 ${SCRIPTDIR}/mysql-exporter.init /etc/init.d/mysql-exporter.init
        ;;
    *)
        echo "Unsupported init system"
        exit 1
        ;;
esac
