#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ "$DIB_INIT_SYSTEM" == "systemd" ]; then
    systemctl daemon-reload
    systemctl enable $(svc-map mysql-exporter)
fi
