#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get --allow-unauthenticated -y install percona-xtrabackup-24 percona-xtradb-cluster-server-5.7 percona-xtradb-cluster-client-5.7

# Don't auto start mysql (we'll start it up in guest)
update-rc.d mysql defaults
update-rc.d mysql disable
